# Generated by Django 3.1.1 on 2021-04-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.CharField(default=True, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
