# Generated by Django 3.1.1 on 2021-04-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20210401_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_of_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_account.account'),
        ),
    ]
