# Generated by Django 3.1.1 on 2021-04-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_auto_20210401_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type_of_account',
        ),
    ]
