# Generated by Django 3.1.1 on 2021-04-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_account_accounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_of_account',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='user_account.account'),
            preserve_default=False,
        ),
    ]
