# Generated by Django 3.1.1 on 2021-04-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_auto_20210401_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type_of_account',
        ),
        migrations.AddField(
            model_name='user',
            name='type_of_account',
            field=models.ManyToManyField(to='user_account.Account'),
        ),
    ]
