# Generated by Django 3.1.1 on 2021-04-01 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_auto_20210401_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type_of_account',
        ),
        migrations.AddField(
            model_name='user',
            name='type_of_account',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='user_account.account'),
            preserve_default=False,
        ),
    ]
