# Generated by Django 3.1.1 on 2021-04-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_auto_20210401_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='AccountType',
            field=models.CharField(choices=[('EM', 'Employed'), ('UEM', 'Unemployed'), ('ST', 'Student')], default='EM', max_length=100),
        ),
    ]
