# Generated by Django 3.1.1 on 2021-04-01 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0011_auto_20210402_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_of_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_account.account'),
        ),
    ]
