# Generated by Django 3.1.1 on 2021-04-01 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0013_auto_20210402_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='AccountType',
            field=models.CharField(choices=[('EM', 'Employed'), ('UEM', 'Unemployed'), ('ST', 'Student')], default='EM', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_of_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.account', to_field='AccountType'),
        ),
    ]
