# Generated by Django 3.1.1 on 2021-04-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0014_auto_20210402_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='AccountType',
            field=models.CharField(choices=[('EM', 'Employed'), ('UEM', 'Unemployed'), ('ST', 'Student')], default='', max_length=100, unique=True),
        ),
    ]
