# Generated by Django 3.1.1 on 2021-04-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0015_auto_20210402_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pending', models.BooleanField(default=False)),
                ('Confirmed', models.BooleanField(default=False)),
                ('Rejected', models.BooleanField(default=False)),
            ],
        ),
    ]
