# Generated by Django 3.1.1 on 2021-04-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0018_auto_20210402_0338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterChoice',
        ),
    ]
